version: '3.9'
services:
  my-sql:
    image: mysql:8.0
    ports:
      - '33093:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_ld
      MYSQL_USER: linh
      MYSQL_PASSWORD: linh

    volumes:
      - './data/mysql:/var/lib/mysql'
